### ISSUE TITLE
Headers are not saved

### ISSUE THREAD

**Issue by baravak** [mll-lab/laravel-graphiql#13]
Headers are not saved even if you enable caching,
after refresh must enable too
![image](https://user-images.githubusercontent.com/953471/230767974-1c6861a2-a0a9-42cd-bc56-56069dc53a15.png)

**Comment by spawnia** [comment]
This package is only a thin integration layer for https://github.com/graphql/graphiql/tree/main/packages/graphiql. This seems like it can be implemented or fixed upstream.

**Comment by khanakia** [comment]
You can click the Setting icon on the bottom left corner and can enable Persist headers
![Screenshot 2023-04-26 at 8 14 13 PM](https://user-images.githubusercontent.com/2174170/234612527-fa126ad3-5077-4438-8ee0-d0cfc234b619.png)
