### ISSUE TITLE
GraphiQL is not defined

### ISSUE THREAD

**Issue by TheMhv** [mll-lab/laravel-graphiql#16]
I got an error when trying to run GraphiQL.

**Uncaught ReferenceError: GraphiQL is not defined**

Investigando o código do repo me deparei com um erro no código do comando _`graphiql:download-assets`_:

[`file_put_contents($publicPath, $cdnPath);`](https://github.com/mll-lab/laravel-graphiql/blob/master/src/DownloadAssetsCommand.php#L61)

The correct code is:

`file_put_contents($publicPath, $contents);`

**Comment by spawnia** [comment]
Fixed with https://github.com/mll-lab/laravel-graphiql/releases/tag/v2.0.2.
