### ISSUE TITLE
Set headers in new tabs

### ISSUE THREAD

**Issue by ucan-lab** [mll-lab/laravel-graphiql#2]
X-CSRF-TOKEN is set when GraphiQL is opened, but not when a new tab is opened.
If you reload the browser, a new tab will be created and X-CSRF-TOKEN will be set.

- ✅ Access to https://localhost/graphiql

<img width="1017" alt="ScreenShot 2022-09-16 11 10 27" src="https://user-images.githubusercontent.com/35098175/190557868-372b8933-6c71-491d-945c-180d7da55c53.png">

X-CSRF-TOKEN is set in Headers.

- ❌ `Add tab` is pressed.

<img width="1017" alt="ScreenShot 2022-09-16 11 10 38" src="https://user-images.githubusercontent.com/35098175/190557883-fdf61ec4-9cb2-407d-a577-d2d3d429c84e.png">

X-CSRF-TOKEN is not set.

- ❌ Browser reload

<img width="1093" alt="ScreenShot 2022-09-16 13 52 14" src="https://user-images.githubusercontent.com/35098175/190559268-d2119ee0-7ebe-4731-b7a7-24d27097d70e.png">

A new tab is created, X-CSRF-TOKEN is set in Headers.
I don't want a new tab to be created when reloading the browser.

Please let me know if there is anything missing.

## Environment

- PHP: 8.1.10
- Laravel: 9.27.0
- mll-lab/laravel-graphiql: 1.0.0

## Process

```
$ php artisan vendor:publish --tag=graphiql-view
```

Add to `resources/views/vendor/graphiql/index.blade.php` head

```
<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
```

Add to `resources/views/vendor/graphiql/index.blade.php` script

```
<script>
    ReactDOM.render(
        React.createElement(GraphiQL, {
            fetcher: GraphiQL.createFetcher({
                url: '{{ url(config('graphiql.endpoint')) }}',
                subscriptionUrl: '{{ config('graphiql.subscription-endpoint') }}',
            }),
            shouldPersistHeaders: true,
            headers: JSON.stringify({
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content,
            }),
        }),
        document.getElementById('graphiql'),
    );
</script>
```

Add to `config/graphiql.php` route.middleware

```
    'route' => [
        'uri' => '/graphiql',
        'name' => 'graphiql',
        'middleware' => ['web'],
        // 'prefix' => '',
        // 'domain' => 'graphql.' . env('APP_DOMAIN', 'localhost'),
    ],
```

```
$ php artisan optimize:clear
```

**Comment by spawnia** [comment]
I can confirm this is how GraphiQL currently works, and according to https://github.com/graphql/graphiql/issues/2145#issuecomment-1230136600 it is the expected behaviour.

Having the header be present in new tabs would be preferrable to me too, so I am going to leave this issue open. The plan is to wait for https://github.com/graphql/graphiql/issues/2145 to be implemented, then we can recommend changing the configuration in a future PR.

**Comment by ucan-lab** [comment]
@spawnia It would be nice to see a header set on the new tab.
Waiting for update, Thank you.

**Comment by spawnia** [comment]
https://github.com/graphql/graphiql/pull/2886 adds the ability to define `defaultHeaders`. I just tested it, will document it and from now on recommend using it.
