### ISSUE TITLE
Failed to load GraphiQl bug with plugin-explorer in version 1.21

### ISSUE THREAD

**Issue by HerlyOlivares** [mll-lab/laravel-graphiql#25]
When loading GraphiQL I get the following error in console:

"GraphiQLPluginExplorer is not defined"

Checking the vendor files, in src/DownloadAssetsCommand.php exactly on line 23:

public const EXPLORER_PLUGIN_PATH_CDN = '//unpkg.com/@graphiql/plugin-explorer/dist/graphiql-plugin-explorer.umd.js';

leads to version 1.21 of plugin-explorer, which is down, To solve it, I replaced that line with:

public const EXPLORER_PLUGIN_PATH_CDN = '//unpkg.com/@graphiql/plugin-explorer@0.1.20/dist/graphiql-plugin-explorer.umd.js';

I used version 1.20 and it worked but it is not the definitive solution.

**Comment by Johnystardust** [comment]
Just encountered the same, thanks for the quick fix @HerlyOlivares.

Would like a definitive solution as well.

**Comment by vitalii-kyktov** [comment]
Got to quick-fix it by publishing view:
```
php artisan vendor:publish --tag=graphiql-view 
```
and hardcoding 
```
<script src="https://unpkg.com/@graphiql/plugin-explorer@0.1.20/dist/graphiql-plugin-explorer.umd.js"></script>
``` 
at line 54 of `/resources/views/vendor/graphiql/index.blade.php`

**Comment by spawnia** [comment]
Fixed with https://github.com/mll-lab/laravel-graphiql/releases/tag/v3.0.2.
