### ISSUE TITLE
graphiql-plugin-explorer.umd.js not found 

### ISSUE THREAD

**Issue by hoangnhiho** [mll-lab/laravel-graphiql#27]
Can't access `/graphiql` because:

`Failed to load resource: the server responded with a status of 404 ()`
`https://unpkg.com/@graphiql/plugin-explorer@0.2.0/dist/graphiql-plugin-explorer.umd.js` is return 404.

```
ReferenceError: GraphiQLPluginExplorer is not defined
    at GraphiQLWithExplorer (graphiql:70:17)
```

Probably has something to do with a new version `v3.1`?

**Comment by spawnia** [comment]
It appears you are not on `v3.1.0`, as it would change the path to end with `/index.umd.js` - see https://github.com/mll-lab/laravel-graphiql/commit/54d7dbe5376ab87a6ea83be11b1431d0af9e2f6c.

**Comment by jovanialferez** [comment]
for those where upgrading is not an option (unsupported laravel version), post from here should help -- https://github.com/mll-lab/laravel-graphiql/issues/25#issuecomment-1606127447
