### ISSUE TITLE
Cannot Access GraphiQL

### ISSUE THREAD

**Issue by TechnicallyGio** [mll-lab/laravel-graphiql#28]
https://flareapp.io/share/KPgQLBq5

Method MLL\GraphiQL\DownloadAssetsCommand::explorerPluginPath does not exist.

Cannot access tool, attempted fresh install. Any idea how to proceed?

**Comment by danielebuso** [comment]
You probably have cached views from the previous version try doing a `php artisan optimize:clear` and see if it works

**Comment by TechnicallyGio** [comment]
You are amazing, thank you!! I cleared every cache that wasn't a view 🤦🏽‍♂️

**Comment by Kreshnik** [comment]
I am facing the same issue.
