### ISSUE TITLE
Cannot subscribe to pusher based WS server

### ISSUE THREAD

**Issue by chrispage1** [mll-lab/laravel-graphiql#29]
Hi,

I'm trying to integrate and test subscriptions with GraphiQL but I'm really struggling. When attempting to execute a subscription I get - 

```
{
  "errors": [
    {
      "message": "Invalid message",
      "stack": "Error: Invalid message\n    at parseMessage (https://unpkg.com/graphiql/graphiql.min.js:20983:11)\n    at socket.onmessage (https://unpkg.com/graphiql/graphiql.min.js:20657:52)"
    }
  ]
}
```

When subscribing to a Pusher channel I get the following message back - 

```
{"event":"pusher:connection_established","data":"{\"socket_id\":\"2814561052.459239379\",\"activity_timeout\":30}"}
```

This connection established response causes the error because it fails the `isMessage` check in graphiql.min.js as once converted to n object, it checks if there a property called `type`. Pusher doesn't have a `type` property and as such fails.

Can it be possible to just ignore Pusher system messages?

Thanks,
Chris.

**Comment by spawnia** [comment]
This package is only a thin integration layer for https://github.com/graphql/graphiql/tree/main/packages/graphiql. This seems like it can be implemented or fixed upstream.
