### ISSUE TITLE
BadMethodCallException - Method MLL\GraphiQL\DownloadAssetsCommand::explorerPluginPath does not exist

### ISSUE THREAD

**Issue by Kreshnik** [mll-lab/laravel-graphiql#30]
I am currently encountering an issue with the `MLL\GraphiQL\DownloadAssetsCommand::explorerPluginPath` method. I'm receiving a `BadMethodCallException` with the message stating "Method MLL\GraphiQL\DownloadAssetsCommand::explorerPluginPath does not exist."

**Steps to reproduce the issue:**

1. Install the latest version of the MLL\GraphiQL package.

**Environment:**

- PHP Version: 8.2
- Laravel Version: 10
- MLL\GraphiQL Version: 3.1

**Attempts to fix:**

I attempted to clear the compiled class file and re-optimize the class loader by running `artisan optimize`, but the issue persisted.

**Comment by spawnia** [comment]
Update your published view.

**Comment by Kreshnik** [comment]
<img width="1452" alt="Screenshot 2023-08-08 at 16 21 20" src="https://github.com/mll-lab/laravel-graphiql/assets/1788349/5d780342-78ab-4e91-9131-8ebcf5fa0c9a">
