### ISSUE TITLE
Sanctum CSRF issue

### ISSUE THREAD

**Issue by chrisneal** [mll-lab/laravel-graphiql#31]
I've followed the instructions for CSRF, and the token is being sent correctly on each request.
<img width="476" alt="image" src="https://github.com/mll-lab/laravel-graphiql/assets/1110269/e0ac0383-908c-47c4-895a-4df3974f7e0a">

The `web` middleware is included in the graphiql config.

```@php
             'middleware' => ['web'],
```

Decoding the XSRF-TOKEN cookie matches the token that is being sent.

The web middleware group consists of the following middleware:

```@php
        [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ]
```

Though I'm still getting a 419 error. CSRF is working correctly from the frontend.

Any ideas?

**Comment by michaelmano** [comment]
I doubt you are still running into this issue. But the fix is here. https://github.com/mll-lab/laravel-graphiql/pull/34

**Comment by benjamin-smith** [comment]
I am not entirely sure what is being discussed in this issue and the PR that is linked, but using `mll-lab/laravel-graphiql:v3.1.0` I was able to set the CSRF token using:

```
headers: {
  'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content,
}
```

This is NOT what is in the README for this version of the package.

**Comment by spawnia** [comment]
The docs have been updated to work with the latest version, and I believe setting `defaultHeaders` is advantageous to using `headers`, as it allows ad-hoc customization. See https://github.com/mll-lab/laravel-graphiql/issues/2#issuecomment-1333725321.
