### ISSUE TITLE
Docs not being loaded

### ISSUE THREAD

**Issue by cwray-tech** [mll-lab/laravel-graphiql#36]
I am using Laravel Lighthouse. I just installed it today, and this package. Ever since installing I'm getting the error below:
```
{
  "errors": [
    {
      "message": "Failed to fetch",
      "stack": "TypeError: Failed to fetch\n    at http://unpkg.com/graphiql/graphiql.min.js:65084:22\n    at Generator.next (<anonymous>)\n    at http://unpkg.com/graphiql/graphiql.min.js:65003:67\n    at new Promise (<anonymous>)\n    at __webpack_modules__.../../graphiql-toolkit/esm/create-fetcher/lib.js.__awaiter (http://unpkg.com/graphiql/graphiql.min.js:64985:10)\n    at http://unpkg.com/graphiql/graphiql.min.js:65083:85\n    at http://unpkg.com/graphiql/graphiql.min.js:64912:54\n    at fetchIntrospectionData (http://unpkg.com/graphiql/graphiql.min.js:58264:40)\n    at http://unpkg.com/graphiql/graphiql.min.js:58286:39\n    at http://unpkg.com/graphiql/graphiql.min.js:58298:5"
    }
  ]
}
```

Is this an issue or have I set something up improperly? I'm using Laravel 9 with PHP 8.

**Comment by spawnia** [comment]
I am very curious how you are getting this error, as it appears to be a JavaScript error that is formatted as JSON. How can this be reproduced?

**Comment by cwray-tech** [comment]
@spawnia this is what is produced when clicking docs. it is displayed in the query results area. This is what was shown after I installed the package and visited the gui.

**Comment by spawnia** [comment]
I can not reproduce the issue in my installation. Have you tried https://github.com/mll-lab/laravel-graphiql#local-assets?

**Comment by cwray-tech** [comment]
I did try that. It is not related to the JavaScript/CSS I don't think. It is having an issue fetching the schema for the docs.

**Comment by spawnia** [comment]
Yeah, `Failed to fetch` probably indicates on issue with your GraphQL server. Anyways, this package is only a slim wrapper around GraphiQL, and the issue does not seem to be related to how GraphiQL is served or how its assets are delivered to the browser. Thus, I believe there is nothing we can change in this package and am closing the issue.
