### ISSUE TITLE
Add explorer plugin

### ISSUE THREAD

**Issue by mostafa-rz** [mll-lab/laravel-graphiql#4]
Can you please add the [explorer plugin](https://github.com/graphql/graphiql/tree/main/packages/graphiql-plugin-explorer) to this playground?

**Comment by spawnia** [comment]
I am open to a pull request that adds it.

**Comment by spawnia** [comment]
Thanks, released with https://github.com/mll-lab/laravel-graphiql/releases/tag/v1.2.0
