### ISSUE TITLE
Feature Request: Ability to Set Default Query on Page Load

### ISSUE THREAD

**Issue by richard-muvirimi** [mll-lab/laravel-graphiql#42]
Thank you for the great library. However, there is no easy way to set the default query when the page is first loaded with the library or a new tab is created. The only way i can see around this is to first export the view, then somehow export the controller so as to pass the default query to use to the view. Looking at the view, the query state variable is set to an empty string by default, which just like the url could have been passed from the controller and there having been read from the exported config file, or have the config dynamically set.

I am looking forward to such a feature, I am also willing to work on it if it's ok.

**Comment by spawnia** [comment]
You can customize this by publishing the view, as described in https://github.com/mll-lab/laravel-graphiql#customization. I do not plan on adding another way to do this.
